FROM python:3.12-slim

WORKDIR /app
COPY . /app

RUN pip install --no-cache-dir --upgrade pip \
 && pip install --no-cache-dir -e .

EXPOSE 8502
CMD ["streamlit", "run", "ai_finance_assistant/src/web_app/streamlit_app.py", "--server.port=8502", "--server.address=0.0.0.0"]
